# Generated by Django 6.0.3 on 2026-07-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('estudiante', 'materia', 'fecha')},
        ),
    ]
