# Generated by Django 6.0.3 on 2026-07-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_asistencia_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='docente',
        ),
    ]
