# Generated by Django 6.0.3 on 2026-07-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_materia_docente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('estudiante', 'actividad')},
        ),
    ]
