# Generated by Django 6.0.3 on 2026-07-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_nota_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='actividad',
            name='puntaje_maximo',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('tarea', 'Tarea'), ('ejercicio', 'Ejercicio'), ('taller', 'Taller'), ('examen', 'Examen')], default='tarea', max_length=20),
        ),
        migrations.AddField(
            model_name='nota',
            name='puntos_obtenidos',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
